export type Subject = {
  id: string
  name: string
  nameNe: string
  emoji: string
  description: string
  color: string
  bgColor: string
  topics: string[]
}

export const SUBJECTS: Subject[] = [
  {
    id: 'mathematics',
    name: 'Mathematics',
    nameNe: 'गणित',
    emoji: '📐',
    description: 'Algebra, Geometry, Calculus',
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.1)',
    topics: ['Algebra', 'Geometry', 'Trigonometry', 'Statistics', 'Calculus'],
  },
  {
    id: 'physics',
    name: 'Physics',
    nameNe: 'भौतिक विज्ञान',
    emoji: '⚡',
    description: 'Mechanics, Waves, Optics',
    color: '#f97316',
    bgColor: 'rgba(249,115,22,0.1)',
    topics: ['Mechanics', 'Thermodynamics', 'Waves', 'Optics', 'Electricity'],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    nameNe: 'रसायन विज्ञान',
    emoji: '🧪',
    description: 'Organic, Inorganic, Physical',
    color: '#10b981',
    bgColor: 'rgba(16,185,129,0.1)',
    topics: ['Organic', 'Inorganic', 'Physical', 'Electrochemistry'],
  },
  {
    id: 'biology',
    name: 'Biology',
    nameNe: 'जीव विज्ञान',
    emoji: '🧬',
    description: 'Botany, Zoology, Genetics',
    color: '#ec4899',
    bgColor: 'rgba(236,72,153,0.1)',
    topics: ['Botany', 'Zoology', 'Genetics', 'Ecology', 'Microbiology'],
  },
  {
    id: 'english',
    name: 'English',
    nameNe: 'अंग्रेजी',
    emoji: '📖',
    description: 'Grammar, Writing, Literature',
    color: '#fbbf24',
    bgColor: 'rgba(251,191,36,0.1)',
    topics: ['Grammar', 'Writing', 'Literature', 'Comprehension'],
  },
  {
    id: 'nepali',
    name: 'Nepali',
    nameNe: 'नेपाली',
    emoji: '🇳🇵',
    description: 'व्याकरण, साहित्य',
    color: '#ef4444',
    bgColor: 'rgba(239,68,68,0.1)',
    topics: ['व्याकरण', 'निबन्ध', 'साहित्य', 'पत्र लेखन'],
  },
  {
    id: 'social',
    name: 'Social Studies',
    nameNe: 'सामाजिक अध्ययन',
    emoji: '🌍',
    description: 'History, Civics, Geography',
    color: '#8b5cf6',
    bgColor: 'rgba(139,92,246,0.1)',
    topics: ['History', 'Civics', 'Geography', 'Economics'],
  },
  {
    id: 'computer',
    name: 'Computer Science',
    nameNe: 'कम्प्युटर विज्ञान',
    emoji: '💻',
    description: 'Programming, Networking',
    color: '#06b6d4',
    bgColor: 'rgba(6,182,212,0.1)',
    topics: ['Programming', 'Networking', 'Database', 'Web'],
  },
  {
    id: 'accounts',
    name: 'Accounts',
    nameNe: 'लेखा',
    emoji: '📊',
    description: 'Bookkeeping, Ledger, Trial Balance',
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.1)',
    topics: ['Bookkeeping', 'Journal', 'Ledger', 'Trial Balance', 'P&L'],
  },
  {
    id: 'economics',
    name: 'Economics',
    nameNe: 'अर्थशास्त्र',
    emoji: '📈',
    description: 'Micro, Macro, Development',
    color: '#84cc16',
    bgColor: 'rgba(132,204,22,0.1)',
    topics: ['Microeconomics', 'Macroeconomics', 'Development', 'Trade'],
  },
  {
    id: 'history',
    name: 'History',
    nameNe: 'इतिहास',
    emoji: '🏛️',
    description: 'Nepal, World, Ancient',
    color: '#a78bfa',
    bgColor: 'rgba(167,139,250,0.1)',
    topics: ['Nepal History', 'World History', 'Ancient History'],
  },
  {
    id: 'geography',
    name: 'Geography',
    nameNe: 'भूगोल',
    emoji: '🗺️',
    description: 'Physical, Human, Maps',
    color: '#34d399',
    bgColor: 'rgba(52,211,153,0.1)',
    topics: ['Physical', 'Human', 'Maps', 'Climate'],
  },
  {
    id: 'optmath',
    name: 'Optional Math',
    nameNe: 'ऐच्छिक गणित',
    emoji: '∑',
    description: 'Trigonometry, Matrices',
    color: '#f472b6',
    bgColor: 'rgba(244,114,182,0.1)',
    topics: ['Trigonometry', 'Matrices', 'Vectors', 'Complex Numbers'],
  },
  {
    id: 'sanskrit',
    name: 'Sanskrit',
    nameNe: 'संस्कृत',
    emoji: '🕉️',
    description: 'Grammar, Translation',
    color: '#fb923c',
    bgColor: 'rgba(251,146,60,0.1)',
    topics: ['Grammar', 'Translation', 'Literature'],
  },
  {
    id: 'health',
    name: 'Health & PE',
    nameNe: 'स्वास्थ्य तथा शारीरिक शिक्षा',
    emoji: '🏃',
    description: 'Anatomy, Sports Science',
    color: '#2dd4bf',
    bgColor: 'rgba(45,212,191,0.1)',
    topics: ['Anatomy', 'Nutrition', 'Sports Science', 'Health'],
  },
]